@startuml
package DocumentBundle {
  object Patient
  object ServiceRequest
  object DiagnosticReport
  object Observation
  object Location
  object Organization
  object Practitioner
  map Task {
    requester=>
    for=>
    basedOn=>
    output=>
    status=>
    owner=>
    location=>
  }
}

Task::requester -u-> Practitioner
Task::basedOn -l-> ServiceRequest
Task::owner -d-> Organization
Task::location -d-> Location
Task::output -r-> DiagnosticReport
DiagnosticReport -r-> Observation
Task::for -u-> Patient
@enduml
