Profile: EmrLisPractitioner
Parent: Practitioner
Id: emr-lab-practitioner
Title: "EMR-LIS Encounter"
Description: "Practitioner resource associated with the Service Request for a lab order generated by the EMR"
* name 1..*
* identifier 1..*