Profile: LaboratoryPractitioner
Parent: Practitioner
Id: laboratory-practitioner
Title: "Laboratory Encounter"
Description: "Practitioner resource associated with the Service Request for a lab order generated by the EMR"
* name 1..*
* identifier 1..*