Profile: LaboratoryEncounter
Parent: Encounter
Id: laboratory-encounter
Title: "Laboratory Encounter"
Description: "Encounter resource associated with the Service Request for a lab order generated by the EMR"

