Profile: EmrLisEncounter
Parent: Encounter
Id: emr-lab-encounter
Title: "EMR-LIS Encounter"
Description: "Encounter resource associated with the Service Request for a lab order generated by the EMR"

